### PR TITLE
Re-enable contact fetching on arm64

### LINKED ISSUE #66: Phone number of incomming call is not resolved in the notification list.
Hello,

for incomming calls the phone number is not resolved in the notification list.

Steps processed:
1. Maintain contact in contact app with name and phone number [fixed line or mobile] (international format) .
2. Receive a call from the number created in step #1, don´t pick up the call.
3. Check enties in notification.

**Result:** Incomming call added as new entry, but number not resolved.

image

UT: 2020-11-06, channel: DEV

### LINKED ISSUE #1561: Unknown missed call
### Illustrations

- Device: Xperia X
- Channel: arm64/RC
- Build: 2020-W37

### Steps to reproduce

miss a call from known contact

### Expected behavior

indicator-messages shows name from contact list

### Actual behavior

indicator-messages shows number instead of name

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
The error that this comment talks about doesn't seem to occur anymore. Easiest bugfix ever.

Fixes https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/66
Fixes https://github.com/ubports/ubuntu-touch/issues/1561

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

File: indicator/messagingmenu.cpp [hunk 1]
```diff
@@ -391,17 +391,12 @@ void MessagingMenu::addCall(const QString &targetId, const QString &accountId, c
     QContactFetchRequest *request = new QContactFetchRequest(this);
     request->setFilter(QContactPhoneNumber::match(targetId));
 
-    //FIXME: on arm64 the connect() statement below fails at runtime with the following output:
-    //QObject::connect: signal not found in QtContacts::QContactFetchRequest
-    // so we just disable it
-#ifndef __aarch64__
```
Comment (mariogrip) [inline indicator/messagingmenu.cpp:397]: Well this is what i call a ultra hack! damn i hope there is not more of these.. :disappointed:

**Review by mariogrip — APPROVED** [review]
LGTM :+1:
